<div class="dash">
    <div class="row-fluid">

        <div class="span6">
            <a href=".#" class="btn btn-primary" data-toggle="modal" data-target="#modalTarefa"><i class="icon-tags icon-2x"></i> <br> Nova Tarefa</a>
            <a href="#printAgenda" class="btn" data-toggle="modal"><i class="icon-print icon-2x"></i> <br> Imprimir Agenda</a>
        </div>
    </div>
</div>

<hr/>

<div id="calendar"></div>

<div id="printAgenda" class="modal hide fade">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3>Imprimir agenda</h3>
    </div>
    <div class="modal-body">

        <form name="formPrintAgenda" action="/tratamento/printagenda" class="form-horizontal ng-pristine ng-valid" target="psicontroleAgenda" method="post">
            <div class="control-group">
                <label class="control-label" for="inputEmail">Data de Início</label>
                <div class="controls">
                    <input type="text" name="inicioAgenda" class="input-small datepicker" value="08/06/2014">
                    <div class="input-append">
                        <span class="add-on"><i class="icon-calendar"></i></span>
                    </div>        
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="inputPassword">Data de Término</label>
                <div class="controls">
                    <input type="text" name="terminoAgenda" class="input-small datepicker" value="14/06/2014">
                    <div class="input-append">
                        <span class="add-on"><i class="icon-calendar"></i></span>
                    </div>        
                </div>
            </div>
        </form>

    </div>
    <div class="modal-footer">
        <a href="#." class="btn" data-dismiss="modal">Fechar</a>
        <a href="#." class="btn btn-primary" id="submitPrintAgenda">Imprimir agenda</a>
    </div>
</div>

<?php include(APPLICATION_PATH . '/views/scripts/partials/novaTarefa.phtml'); ?>

<script>
    $('#calendar').fullCalendar({
        header: {
            left: 'prev,next today',
            center: 'title',
            right: 'month,agendaWeek,agendaDay'
        },
        height: 650,
        axisFormat: 'H:mm',
        lang: 'pt-br',
        weekNumbers: false,
        editable: false,
        events: '/tarefas/eventos'
    });
</script>
