<div class="row-fluid">
    <div class="span12">
        <h2><i class="icon-tags"></i> Tarefas</h2>

        <hr>

        <p class="pull-left"><a href=".#" class="btn btn-primary" data-toggle="modal" data-target="#modalTarefa"><i class="icon-tags"></i> &nbsp; Nova Tarefa</a></p>

        <br/>

        <div class="row-fluid" id="conteudoCanvas">

            <ul id="opcoesTarefa">
                <li><a href="/tarefas" class="opcaoTarefa <?php echo ($this->situacao == null ? 'selected' : '') ?>" rel="0">Tarefas pendentes</a></li>
                <li class="spacer">|</li>
                <li><a href="/tarefas/index/situacao/CON" class="opcaoTarefa <?php echo ($this->situacao == 'CON' ? 'selected' : '') ?>" rel="1">Tarefas finalizadas</a></li>
                <li class="spacer">|</li>
                <li><a href="/tarefas/index/situacao/CAN" class="opcaoTarefa <?php echo ($this->situacao == 'CAN' ? 'selected' : '') ?>" rel="2">Tarefas Canceladas</a></li>
            </ul>

            <div class="clearfix"></div>

            <ul class="canvasListagem" id="listComentarios">

                <?php foreach ($this->tarefas as $tarefa) : ?>
                    <li class="item pb10 comentsPg0">
                        <span class="imgAvatar imgUsuario"></span><strong><?php echo $tarefa->findParentRow('Usuario')->nome; ?></strong>

                        <p>#<?php echo str_pad($tarefa->id, 6, '0', STR_PAD_LEFT); ?> <br/> <?php echo $tarefa->texto; ?></p>

                        <span class="bottom c999">
                            <span rel="tooltip" class="data ml20">
                                tarefa agendada para <?php echo date("d/m/Y", strtotime($tarefa->dtTarefa)); ?>
                                às  <?php echo date("H:i", strtotime($tarefa->horaTarefa)); ?>
                                | 
                                Situação: <?php echo $this->tarefa->getSituacao($tarefa->situacao); ?>
                                |
                                Cliente relacionado : <?php echo ($tarefa->id_cliente == null ? 'Nenhum' : $tarefa->findParentRow('Cliente')->nome); ?>
                            </span>
                        </span>

                        <ul class="menu">
                            <li><a href="/tarefas/visualizar/id/<?php echo $tarefa->id; ?>" class="lnkEditarComentario cboxElement">Visualizar</a></li>
                        </ul>

                        <div class="clear"></div>
                    </li>

                <?php endforeach; ?>
            </ul>
        </div>
    </div>
</div>

<?php include(APPLICATION_PATH .'/views/scripts/partials/novaTarefa.phtml'); ?>