<div>

    <div class="row-fluid">
        <div class="span6">
            <h2>Tarefa #<?php echo str_pad($this->tarefa->id, 6, '0', STR_PAD_LEFT); ?></h2>
        </div>
    </div>

    <hr>

    <div class="row-fluid">
        <div class="span3 well">

            <div id="dadosSolicitacao">
                <h4>Informações</h4>
                <p><strong>Cliente Vinculado:</strong> <?php echo ($this->tarefa->id_cliente == null ? 'Não Definido' : $this->tarefa->findParentRow('Cliente')->nome); ?></p>
                <p><strong>Situação:</strong> <?php echo $this->objTarefa->getSituacao($this->tarefa->situacao); ?></p>
                <p><strong>Vencimento:</strong> <?php echo date("d/m/Y", strtotime($this->tarefa->dtTarefa)); ?></p>
                <p><strong>Solicitante:</strong> <?php echo $this->tarefa->findParentRow('Usuario')->nome; ?></p>

            </div>

            <hr/>

            <h4 id="toggleDadosSolicitante" style="cursor: pointer;">Usuários relacionados</h4>

            <div id="solicitante" style="display: block;">
                <ul>
                    <?php foreach ($this->tarefa->findDependentRowset('TarefaUsuario') as $u) : ?>
                        <li><?php echo $u->findParentRow('Usuario')->nome; ?></li>
                    <?php endforeach; ?>
                </ul>
            </div>

            <hr/>

            <h4>Ações</h4>

            <?php if ($this->tarefa->situacao == 'PEN') : ?>
                <p>
                    <a href="javascript:void(0);" id="solicitarPosicao" class="btn btn-small btn-primary actions" data-toggle="modal" data-target="#modalAcompanhamento">
                        <i class="icon-question"></i> &nbsp; Acompanhamento
                    </a>
                </p>
                <p>
                    <a href="javascript:void(0);" class="btn btn-small btn-success actions" data-toggle="modal" data-target="#modalConcluir">
                        <i class="icon-ok"></i> &nbsp; Concluir Tarefa
                    </a>
                </p>

                <p>
                    <a href="javascript:void(0);" id="cancelarSolicitacao" class="btn btn-small btn-danger actions" data-toggle="modal" data-target="#modalCancelar">
                        <i class="icon-remove"></i> &nbsp; Cancelar Tarefa
                    </a>
                </p>
            <?php endif; ?>

            <hr />

        </div>
        <div class="span9">
            <div id="descricao">
                <h4 class="fLeft">Descrição</h4>
                <p><?php echo $this->tarefa->texto; ?></p>
            </div>

            <hr/>

            <ul class="nav nav-tabs">
                <li class="active"><a href="#historico" data-toggle="tab"><i class="icon-file-alt"></i> Acompanhamentos</a></li>
                <li class=""><a href="#anexos" data-toggle="tab"><i class="icon-file-alt"></i> Anexos</a></li>
            </ul>

            <div class="tab-content clearfix">
                <div class="tab-pane active" id="historico">
                    <div class="activities">

                        <?php foreach ($this->objTarefa->getHistorico($this->tarefa->id) as $historico) : ?>
                            <div class="activity">
                                <div class="clearfix muted">
                                    <span class="fLeft"><small><?php echo $historico->findParentRow('Usuario')->nome; ?></small></span>
                                    <span class="fRight"><small><?php echo date("d/m/Y H:i:s", strtotime($historico->quando)); ?></small></span>
                                </div>
                                <div class="media">
                                    <span class="pull-left"><i class="icon-file-alt"></i></span>
                                    <div class="media-body">
                                        <?php echo nl2br($historico->texto); ?>                                   
                                    </div>
                                    <?php if ($historico->id_usuario == $this->idUsuario && $this->tarefa->situacao == 'PEN') : ?>
                                        <a class="delete fRight" href="/tarefas/remove-acompanhamento/id/<?php echo $historico->id; ?>/tarefa/<?php echo $this->tarefa->id ?>">Excluir</a>
                                    <?php endif; ?>
                                </div>				
                            </div>

                            <hr>
                        <?php endforeach; ?>

                    </div>
                </div>

                <div class="tab-pane" id="anexos">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>Arquivo</th>
                                <th>Usuário</th>
                                <th>Visualizar</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->tarefa->findDependentRowset('Anexo') as $anexo): ?>
                                <tr>
                                    <td><?php echo $anexo->nome; ?></td>
                                    <td><?php echo $anexo->findParentRow('Usuario')->nome; ?></td>
                                    <td><a href="/<?php echo $anexo->caminho; ?>" target="_blank">Visualizar</a></td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal Concluir -->
    <div id="modalConcluir" class="modal hide fade">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h3>Concluir Tarefa</h3>
        </div>
        <form method="post" action="/tarefas/concluir" id="formConcluir">
            <div class="modal-body">
                <input type="hidden" name="id_usuario" value="<?php echo $this->idUsuario; ?>">
                <input type="hidden" name="id_tarefa" value="<?php echo $this->tarefa->id; ?>">
                <h4>Tem certeza de que gostaria concluir esta tarefa?</h4>
                <p>Depois de finalizada, ela não poderá ser reaberta.</p>
            </div>
            <div class="modal-footer">
                <a href="#." class="btn" data-dismiss="modal">Não</a>
                <input type="submit" value="Sim" class="btn btn-primary">
            </div>
        </form>
    </div>
    
    <!-- Modal Cancelar -->
    <div id="modalCancelar" class="modal hide fade">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h3>Cancelar Tarefa</h3>
        </div>
        <form method="post" action="/tarefas/cancelar" id="formCancelar">
            <div class="modal-body">
                <input type="hidden" name="id_usuario" value="<?php echo $this->idUsuario; ?>">
                <input type="hidden" name="id_tarefa" value="<?php echo $this->tarefa->id; ?>">
                <h4>Tem certeza de que gostaria cancelar esta tarefa?</h4>
                <p>Depois de cancelar, ela não poderá ser reaberta.</p>
            </div>
            <div class="modal-footer">
                <a href="#." class="btn" data-dismiss="modal">Não</a>
                <input type="submit" value="Sim" class="btn btn-primary">
            </div>
        </form>
    </div>

    <!-- Modal Classificar -->
    <div id="modalAcompanhamento" class="modal hide fade">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h3>Registrar Acompanhamento</h3>
        </div>
        <form method="post" action="/tarefas/acompanhamento" id="formAcompanhamento" enctype="multipart/form-data">
            <div class="modal-body">

                <div class="row-fluid">
                    <div class="span12">
                        <div class="control-group">
                            <div class="control-label">
                                <label>Comentário</label>
                            </div>
                            <div class="controls">
                                <textarea name="texto" rows="5" style="width: 97%;"></textarea>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">
                                <label for="anexo">Anexo</label>
                            </label>
                            <div class="controls">
                                <input type="file" name="arquivo" id="anexo"/>							
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <input type="hidden" name="id_tarefa" value="<?php echo $this->tarefa->id; ?>" />
            <input type="hidden" name="id_usuario" value="<?php echo $this->idUsuario; ?>" />

            <div class="modal-footer">
                <a href="#." class="btn" data-dismiss="modal">Cancelar</a>
                <input type="submit" value="Gravar" class="btn btn-primary">
            </div>
        </form>
    </div>


    <script type="text/javascript">

        $("#toggleDadosSolicitante").click(function() {
            $("#solicitante").toggle('slow');
        });

        $('#formAcompanhamento').validate({
            rules: {
                texto: {required: true}
            }
        });

    </script>

</div>