<div>

    <div class="row-fluid">
        <div class="span6">
            <h2>Tarefa #<?php echo str_pad($this->tarefa->id, 6, '0', STR_PAD_LEFT); ?></h2>
        </div>
    </div>

    <hr>

    <div class="row-fluid">
        <div class="span3 well">

            <div id="dadosSolicitacao">
                <h4>Informações</h4>
                <p><strong>Cliente Vinculado:</strong> <?php echo ($this->tarefa->id_cliente == null ? 'Não Definido' : $this->tarefa->findParentRow('Cliente')->nome); ?></p>
                <p><strong>Situação:</strong> <?php echo $this->objTarefa->getSituacao($this->tarefa->situacao); ?></p>
                <p><strong>Vencimento:</strong> <?php echo date("d/m/Y", strtotime($this->tarefa->dtTarefa)); ?></p>
                <p><strong>Solicitante:</strong> <?php echo $this->tarefa->findParentRow('Usuario')->nome; ?></p>

            </div>

            <hr/>

            <h4 id="toggleDadosSolicitante" style="cursor: pointer;">Usuários relacionados</h4>

            <div id="solicitante" style="display: block;">
                <ul>
                    <?php foreach ($this->tarefa->findDependentRowset('TarefaUsuario') as $u) : ?>
                        <li><?php echo $u->findParentRow('Usuario')->nome; ?></li>
                    <?php endforeach; ?>
                </ul>
            </div>

            <hr/>

            <h4>Ações</h4>

            <p>
                <a href="javascript:void(0);" id="solicitarPosicao" class="btn btn-small btn-primary actions" data-toggle="modal" data-target="#modalAcompanhamento">
                    <i class="icon-question"></i> &nbsp; Registrar Acompanhamento
                </a>
            </p>

            <p>
                <a href="javascript:void(0);" class="btn btn-small btn-success actions" data-toggle="modal" data-target="#modalConcluir">
                    <i class="icon-ok"></i> &nbsp; Concluir Tarefa
                </a>
            </p>

            <p>
                <a href="/solicitacoes/cancela-solicitacao/id/" id="cancelarSolicitacao" class="btn btn-small btn-danger actions">
                    <i class="icon-remove"></i> &nbsp; Cancelar Tarefa
                </a>
            </p>

            <hr />

        </div>
        <div class="span9">
            <div id="descricao">
                <h4 class="fLeft">Descrição</h4>
                <p><?php echo $this->tarefa->texto; ?></p>
            </div>

            <hr/>
            <h4>Histórico da tarefa</h4>
            <hr/>

            <div class="activity">
                <div class="clearfix muted">
                    <span class="fLeft"><small></small></span>
                    <span class="fRight"><small></small></span>
                </div>
                <div class="media">
                    <span class="pull-left"><i class="icon-file-alt"></i></span>
                    <div class="media-body">

                    </div>
                </div>				
            </div>

            <hr/>

        </div>
    </div>

    <!-- Modal Concluir -->
    <div id="modalConcluir" class="modal hide fade">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h3>Concluir Tarefa</h3>
        </div>
        <form method="post" action="/solicitacoes/concluir" id="formConcluir">
            <div class="modal-body">
                <input type="hidden" name="idtratamento" value="43">
                <h4>Tem certeza de que gostaria concluir esta tarefa?</h4>
                <p>Depois de finalizada, ela não poderá ser reaberta.</p>
            </div>
            <div class="modal-footer">
                <a href="#." class="btn" data-dismiss="modal">Cancelar</a>
                <input type="submit" value="Concluir" class="btn btn-primary">
            </div>
        </form>
    </div>

    <!-- Modal Classificar -->
    <div id="modalAcompanhamento" class="modal hide fade">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h3>Classificar Solicitação</h3>
        </div>
        <form method="post" action="/tarefas/acompanhar" id="formClassificar">
            <div class="modal-body">

                <div class="row-fluid">
                    <div class="span12">
                        <div class="control-group">
                            <div class="control-label">
                                <label>Comentário</label>
                            </div>
                            <div class="controls">
                                <textarea name="texto" ></textarea>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">
                                <label for="codigo">Código</label>
                            </label>
                            <div class="controls">
                                <input type="file" name="arquivo" />							
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="modal-footer">
                <a href="#." class="btn" data-dismiss="modal">Cancelar</a>
                <input type="submit" value="Classificar" class="btn btn-primary">
            </div>
        </form>
    </div>


    <script type="text/javascript">

        $("#toggleDadosSolicitante").click(function() {
            $("#solicitante").toggle('slow');
        });

        $(function() {
            $("#cancelarSolicitacao").click(function(e) {
                e.preventDefault();
                var url = $(this).attr('href');
                var answer = confirm("Confirma o Cancelamento da Solicitação?");
                if (answer) {
                    window.location = url;
                } else {
                    return false;
                }
            });
        });

        $('#formTransferir').validate({
            rules: {
                terceiro: {required: true}
            }
        });

        $('#formConcluir').validate({
            rules: {
                descricao: {required: true}
            }
        });

        $('#formClassificar').validate({
            rules: {
                tipo: {required: true},
                processo: {required: true},
                id_itemprocesso: {required: true},
                previsaoConclusao: {required: true}
            }
        });

    </script>

</div>