<div class="row-fluid">
    <h2>Editar Usuário</h2>

    <hr>

    <form method="post" class="form-horizontal" id="usuario">
        <div class="row-fluid">
            <div class="span1 txtCenter">
                <i class="icon-user icon-3x muted"></i>
            </div>
            <div class="span11">
                <div class="control-group">
                    <label class="control-label">
                        <label for="codigo">Código</label>
                    </label>
                    <div class="controls">
                        <input type="text" name="codigo" class="input-xlarge" value="<?php echo $this->cliente->codigo; ?>">							
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">
                        <label for="nome">Nome</label>
                    </label>
                    <div class="controls">
                        <input type="text" name="nome" class="input-xlarge" value="<?php echo $this->cliente->nome; ?>">							
                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label">
                        <label for="estado">Categoria</label>
                    </label>
                    <div class="controls">
                        <select name="estado" id="estado" class="input-xlarge">
                            <option value="">Selecione o estado</option>
                            <option <?php echo ($this->cliente->estado == 'AC' ? 'selected="selected"' : ''); ?> value="AC">Acre</option>
                            <option <?php echo ($this->cliente->estado == 'AL' ? 'selected="selected"' : ''); ?> value="AL">Alagoas</option>
                            <option <?php echo ($this->cliente->estado == 'AP' ? 'selected="selected"' : ''); ?> value="AP">Amapá</option>
                            <option <?php echo ($this->cliente->estado == 'AM' ? 'selected="selected"' : ''); ?> value="AM">Amazonas</option>
                            <option <?php echo ($this->cliente->estado == 'BA' ? 'selected="selected"' : ''); ?> value="BA">Bahia</option>
                            <option <?php echo ($this->cliente->estado == 'CE' ? 'selected="selected"' : ''); ?> value="CE">Ceará</option>
                            <option <?php echo ($this->cliente->estado == 'DF' ? 'selected="selected"' : ''); ?> value="DF">Distrito Federal</option>
                            <option <?php echo ($this->cliente->estado == 'ES' ? 'selected="selected"' : ''); ?> value="ES">Espirito Santo</option>
                            <option <?php echo ($this->cliente->estado == 'GO' ? 'selected="selected"' : ''); ?> value="GO">Goiás</option>
                            <option <?php echo ($this->cliente->estado == 'MA' ? 'selected="selected"' : ''); ?> value="MA">Maranhão</option>
                            <option <?php echo ($this->cliente->estado == 'MT' ? 'selected="selected"' : ''); ?> value="MT">Mato Grosso</option>
                            <option <?php echo ($this->cliente->estado == 'MS' ? 'selected="selected"' : ''); ?> value="MS">Mato Grosso do Sul</option>
                            <option <?php echo ($this->cliente->estado == 'MG' ? 'selected="selected"' : ''); ?> value="MG">Minas Gerais</option>
                            <option <?php echo ($this->cliente->estado == 'PA' ? 'selected="selected"' : ''); ?> value="PA">Pará</option>
                            <option <?php echo ($this->cliente->estado == 'PB' ? 'selected="selected"' : ''); ?> value="PB">Paraiba</option>
                            <option <?php echo ($this->cliente->estado == 'PR' ? 'selected="selected"' : ''); ?> value="PR">Paraná</option>
                            <option <?php echo ($this->cliente->estado == 'PE' ? 'selected="selected"' : ''); ?> value="PE">Pernambuco</option>
                            <option <?php echo ($this->cliente->estado == 'PI' ? 'selected="selected"' : ''); ?> value="PI">Piauí</option>
                            <option <?php echo ($this->cliente->estado == 'RJ' ? 'selected="selected"' : ''); ?> value="RJ">Rio de Janeiro</option>
                            <option <?php echo ($this->cliente->estado == 'RN' ? 'selected="selected"' : ''); ?> value="RN">Rio Grande do Norte</option>
                            <option <?php echo ($this->cliente->estado == 'RS' ? 'selected="selected"' : ''); ?> value="RS">Rio Grande do Sul</option>
                            <option <?php echo ($this->cliente->estado == 'RO' ? 'selected="selected"' : ''); ?> value="RO">Rondônia</option>
                            <option <?php echo ($this->cliente->estado == 'RR' ? 'selected="selected"' : ''); ?> value="RR">Roraima</option>
                            <option <?php echo ($this->cliente->estado == 'SC' ? 'selected="selected"' : ''); ?> value="SC">Santa Catarina</option>
                            <option <?php echo ($this->cliente->estado == 'SP' ? 'selected="selected"' : ''); ?> value="SP">São Paulo</option>
                            <option <?php echo ($this->cliente->estado == 'SE' ? 'selected="selected"' : ''); ?> value="SE">Sergipe</option>
                            <option <?php echo ($this->cliente->estado == 'TO' ? 'selected="selected"' : ''); ?> value="TO">Tocantis</option>
                        </select>
                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label">
                        <label for="cnpj">Cnpj</label>
                    </label>
                    <div class="controls">
                        <input type="text" name="cnpj" class="input-xlarge" value="<?php echo $this->cliente->cnpj; ?>">							
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">
                        <label for="telefone">Telefone</label>
                    </label>
                    <div class="controls">
                        <input type="text" name="telefone" class="input-xlarge tel" value="<?php echo $this->cliente->telefone; ?>">							
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">
                        <label for="email">E-mail</label>
                    </label>
                    <div class="controls">
                        <input type="text" name="email" class="input-xlarge" value="<?php echo $this->cliente->telefone; ?>">							
                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label">
                        <label for="descricao">Descrição</label>
                    </label>
                    <div class="controls">
                        <textarea name="descricao" class="input-xlarge"><?php echo $this->cliente->descricao; ?></textarea>							
                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label">
                        <label for="categoria">Categoria</label>
                    </label>
                    <div class="controls">
                        <select name="id_categoria" id="categoria" class="input-xlarge">
                            <option value="">Selecione uma Categoria</option>
                            <?php foreach ($this->categorias as $categoria) : ?>
                                <?php $select = ($categoria->id == $this->cliente->id_categoria ? 'selected="selected"' : ""); ?>
                                <option <?php echo $select; ?> value="<?php echo $categoria->id; ?>"><?php echo $categoria->nome; ?></option>
                            <?php endforeach; ?>
                        </select>							
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">
                        <label for="responsavel">Responsável</label>
                    </label>
                    <div class="controls">
                        <select name="id_responsavel" id="empresa" class="input-xlarge">
                            <option value="">Selecione um Responsável</option>
                            <?php foreach ($this->usuarios as $usuario) : ?>
                                <?php $select = ($usuario->id == $this->cliente->id_responsavel ? 'selected="selected"' : ""); ?>
                                <option <?php echo $select; ?> value="<?php echo $usuario->id; ?>"><?php echo $usuario->nome; ?></option>
                            <?php endforeach; ?>
                        </select>							
                    </div>
                </div>
            </div>
        </div>

        <div class="form-actions">
            <input type="submit" id="submitbutton" class="btn btn-primary" value="Salvar">  
            <a href="/clientes" class="btn">Cancelar</a>
        </div>

    </form>

    <script type="text/javascript">
        $('#usuario').validate({
            rules: {
                nome: {required: true, minLenght: 2},
                email: {required: true, email: true},
                role: {required: true},
                id_empresa: {required: true},
                id_departamento: {required: true}
            }
        });

        $('#empresa').change(function() {
            $("#departamento").html('<option value="">Carregando....</option>');
            $.getJSON('/usuarios/departamentos', {empresa: $(this).val(), ajax: 'true'}, function(j) {
                var options = '<option value="">Selecione um Departamento</option>';
                for (var i = 0; i < j.length; i++) {
                    options += '<option value="' + j[i].id + '">' + j[i].nome + '</option>';
                }
                $('#departamento').html(options).show();
            });
        });
    </script>  

</div>
