<?php $hst = new Historico(); ?>
<div id="conteudoCanvas">

    <div id="canvasHeader">
        <div id="headerImagem" class="imgEmpresa"></div>

        <h1><?php echo $this->cliente->nome; ?></h1>

        <ul class="listaInfo">
            <li><span>Categoria:</span> <?php echo ($this->cliente->id_categoria == null ? 'Não definido' : $this->cliente->findParentRow('Categoria')->nome); ?></li>
            <li><span>Telefone:</span> <?php echo ($this->cliente->telefone == null ? 'Não definido' : $this->cliente->telefone); ?></li>
        </ul>

        <ul id="headerSubMenu">
            <li><span>Ver histórico</span></li>
            <li class="spacer">|</li>
            <li><a href="/clientes/pessoas/id/<?php echo $this->cliente->id; ?>" title="Ver pessoas deste Cliente">Ver pessoas</a></li>
            <li class="spacer">|</li>
            <li><a href="/clientes/editar/id/<?php echo $this->cliente->id; ?>" title="Editar este Cliente">Editar</a></li>
            <li class="spacer">|</li>
            <li><a href="/clientes/remover/id/<?php echo $this->cliente->id; ?>" title="Excluir este Cliente">Excluir</a></li>
        </ul><!--headerSubMenu-->

        <div class="clear"></div>

    </div><!--canvasHeader-->

    <form action="/clientes/grava-historico" id="formComentar" method="post" enctype="multipart/form-data">
        <input type="hidden" name="id_cliente" value="<?php echo $this->cliente->id; ?>" />
        <input type="hidden" name="id_usuario" value="<?php echo $this->idUsuario; ?>" />
        <fieldset>
            <label for="formComentario">O que foi feito e qual o próximo passo?</label>
            <textarea name="texto" id="formComentario"></textarea>
        </fieldset>

        <input type="submit" value="Gravar comentário" class="btn btn-info btn-mini pull-right" id="btnComentar">

        <a href="javascript:void(0);" id="lnkAdicionarArquivosImagens" title="Adicionar arquivos e imagens">Adicionar arquivos e imagens</a> ou,
        <a href="javascript:void(0);" id="lnkDefinirAgendamento" title="definir agendamento">definir agendamento</a>

        <div class="clear"></div>
    </form>

    <ul class="canvasListagem" id="listComentarios">

        <?php foreach ($this->cliente->findDependentRowset('Historico', null, $hst->select()->order('id desc')) as $historico) : ?>
            <li class="item pb10 comentsPg0">
                <span class="imgAvatar imgUsuario"></span><strong><?php echo $historico->findParentRow('Usuario')->nome; ?></strong>

                <p><?php echo $historico->texto; ?></p>

                <span class="bottom c999">
                    <span rel="tooltip" class="data ml20"><?php echo date("d/m/Y", strtotime($historico->quando)); ?> às <?php echo date("H:i:s", strtotime($historico->quando)); ?></span>
                </span>

                <ul class="menu">
                    <li><a href="" class="lnkEditarComentario cboxElement">Editar</a></li>
                    <li class="spacer">|</li>
                    <li><a href="/clientes/remove-historico/id/<?php echo $historico->id; ?>" class="lnkExcluirComentario" title="Excluir este comentário">Excluir</a></li>
                </ul>

                <div class="clear"></div>
            </li>

        <?php endforeach; ?>
    </ul>
</div>

<script type="text/javascript">
    $('#formComentar').validate({
        rules: {
            texto: {required: true, minLenght: 3}
        }
    });
</script>  