<?php $hst = new Historico(); ?>
<div id="conteudoCanvas">

    <div id="canvasHeader">
        <div id="headerImagem" class="imgEmpresa"></div>

        <h1><?php echo $this->cliente->nome; ?></h1>

        <ul class="listaInfo">
            <li><span>Categoria:</span> <?php echo ($this->cliente->id_categoria == null ? 'Não definido' : $this->cliente->findParentRow('Categoria')->nome); ?></li>
            <li><span>Telefone:</span> <?php echo ($this->cliente->telefone == null ? 'Não definido' : $this->cliente->telefone); ?></li>
        </ul>

        <ul id="headerSubMenu">
            <li><span>Ver histórico</span></li>
            <li class="spacer">|</li>
            <li><a href="/clientes/pessoas/id/<?php echo $this->cliente->id; ?>" title="Ver pessoas deste Cliente">Ver pessoas</a></li>
            <li class="spacer">|</li>
            <li><a href="/clientes/editar/id/<?php echo $this->cliente->id; ?>" title="Editar este Cliente">Editar</a></li>
            <li class="spacer">|</li>
            <li><a href="/clientes/remover/id/<?php echo $this->cliente->id; ?>" title="Excluir este Cliente">Excluir</a></li>
        </ul><!--headerSubMenu-->

        <div class="clear"></div>

    </div><!--canvasHeader-->

    <form action="/clientes/grava-historico" id="formComentar" method="post" enctype="multipart/form-data">
        <input type="hidden" name="id_cliente" value="<?php echo $this->cliente->id; ?>" />
        <input type="hidden" name="id_usuario" value="<?php echo $this->idUsuario; ?>" />
        <fieldset>
            <label for="formComentario">O que foi feito e qual o próximo passo?</label>
            <textarea name="texto" id="formComentario"></textarea>
        </fieldset>

        <fieldset id="setDtAgenDocsImgs">

            <div id="setDtAgen" style="display: none;">
                <a href="javascript:void(0)" class="btnFechar" id="btnFechar" title="Cancelar agendamento"></a>
                <label>Tarefa para quando?</label>
                <input type="text" name="dtAgendamento" id="formDtAgendamento" class=" input-small datepicker" />
                às &nbsp; 
                <input type="text" name="horaAgendamento" id="formHoraAgendamento" class=" input-mini hora" />

                <label>A quem se destina?</label>

                <ul class="ulSelUsuarios">
                    <?php foreach ($this->usuarios as $usuario) : ?>
                        <li>
                            <label>
                                <input type="checkbox" required minlength="1" name="usuario[]" value="<?php echo $usuario->id; ?>" class="checkbox" <?php echo ($this->idUsuario == $usuario->id ? 'checked="checked"' : ''); ?> /> 
                                <?php echo ($this->idUsuario == $usuario->id ? 'A mim' : $usuario->nome); ?><em></em>
                            </label>
                        </li>
                    <?php endforeach; ?>
                </ul><!--ulSelUsuarios-->

                <div class="clear"></div>

            </div><!--setDtAgen-->

            <div id="setDocsImgs" style="display: none;">
                <ul>
                    <li class="liImg">
                        <input class="file" name="arquivo[]" type="file" required />
                        <a href="javascript:void(0);" class="btnExcluir">
                            <img src="/img/icone-btn-fechar-cinza.gif" alt="Excluir">
                        </a>
                    </li>
                    <li>
                        <a href="javascript:void(0);" id="lnkAdicionarNovoArquivo">adicionar um arquivo</a>
                    </li>
                </ul>
            </div><!--setDocsImgs-->
        </fieldset>

        <input type="submit" value="Gravar comentário" class="btn btn-info btn-mini pull-right" id="btnComentar">

        <a href="javascript:void(0);" id="lnkAdicionarArquivosImagens" title="Adicionar arquivos">Adicionar arquivos</a> ou,
        <a href="javascript:void(0);" id="lnkDefinirAgendamento" title="Definir como tarefa">Definir como tarefa</a>

        <div class="clear"></div>
    </form>

    <ul class="canvasListagem" id="listComentarios">

        <?php foreach ($this->cliente->findDependentRowset('Historico', null, $hst->select()->order('id desc')) as $historico) : ?>
            <li class="item pb10 comentsPg0">
                <span class="imgAvatar imgUsuario"></span><strong><?php echo $historico->findParentRow('Usuario')->nome; ?></strong>

                <p><?php echo $historico->texto; ?></p>

                <ul class="listaArquivos">
                    <?php foreach ($historico->findDependentRowset('Anexo') as $anexo) : ?>
                        <li>
                            <a href="/<?php echo $anexo->caminho; ?>" target="_blank"><?php echo $anexo->nome; ?></a>
                        </li>
                    <?php endforeach; ?>
                </ul>

                <span class="bottom c999">
                    <span rel="tooltip" class="data ml20">
                        <?php echo date("d/m/Y", strtotime($historico->quando)); ?> às <?php echo date("H:i:s", strtotime($historico->quando)); ?>
                        <?php if ($historico->tarefa == 1) : ?>
                            , <a href="/tarefas/visualizar/id/<?php echo $historico->findDependentRowset('Tarefa')[0]->id; ?>">tarefa agendada para <?php echo date("d/m/Y", strtotime($historico->findDependentRowset('Tarefa')[0]->dtTarefa)); ?></a>
                        <?php endif; ?>

                    </span>
                </span>

                <ul class="menu">
                    <?php if ($this->idUsuario == $historico->id_usuario) : ?>
                        <li><a href="/clientes/remove-historico/id/<?php echo $historico->id; ?>/cliente/<?php echo $this->cliente->id; ?>" class="lnkExcluirComentario delete" title="Excluir este comentário">Excluir</a></li>
                    <?php endif; ?>
                </ul>

                <div class="clear"></div>
            </li>

        <?php endforeach; ?>
    </ul>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('#formComentar').validate({
            rules: {
                dtAgendamento: {required: true},
                horaAgendamento: {required: true},
                texto: {required: true},
                usuario: {required: true}
            }
        });

        var getHtmlNovaImagem = function() {
            return '<li class="liImg">' +
                    '<input class="file" title="" name="arquivo[]" type="file" required />' +
                    '<a href="javascript:void(0);" class="btnExcluir">' +
                    '<img src="/img/icone-btn-fechar-cinza.gif" alt="Excluir">' +
                    '</a></li>';
        };

        $("#setDocsImgs #lnkAdicionarNovoArquivo").click(function() {
            $(this).parent().before(getHtmlNovaImagem());
        });

        $("body").on('click', '.btnExcluir', function() {
            $(this).parent().remove();
        });

        $("#lnkDefinirAgendamento").click(function() {
            if ($("#setDtAgen").is(":visible"))
                cancelarAgendamento();
            else {
                mostraAgendamento();
            }
        });

        $("#btnFechar").click(function() {
            cancelarAgendamento();
        });

        $("#lnkAdicionarArquivosImagens").click(function() {
            if ($("#setDocsImgs").is(":visible")) {
                $("#setDocsImgs").slideUp('fast', function() {
                    cancelarArquivos();
                });
            } else {
                mostrarArquivos();
            }
        });

        var mostraAgendamento = function() {
            $("#setDtAgen").slideDown('fast');
            $("#lnkDefinirAgendamento").attr('title', 'cancelar tarefa').html("cancelar tarefa");
            $(".ulSelUsuarios").find("li input[type=checkbox]:first").attr('checked', true);
        };

        var cancelarAgendamento = function() {
            $(".ulSelUsuarios").find("li input[type=checkbox]").attr('checked', false);
            $("#setDtAgen").hide();
            $("#setDtAgen").slideUp('fast');
            $("#lnkDefinirAgendamento").attr('title', 'Definir como tarefa').html("Definir como tarefa");
            $("#formDtAgendamento").val('');
            $("#formHoraAgendamento").val('');
        };

        var mostrarArquivos = function() {
            $("#setDocsImgs").slideDown('fast');
            $("#lnkAdicionarArquivosImagens").attr('title', 'Cancelar arquivos').html("Cancelar arquivos");
        };

        var cancelarArquivos = function() {
            $("#setDocsImgs li.liImg, #setDocsImgs li.liDoc").remove();
            $("#lnkAdicionarArquivosImagens").attr('title', 'Adicionar arquivos').html("Adicionar Arquivos");
        };
    });
</script>  