<div class="row-fluid">
    <div class="span12">
        <h2><i class="icon-user"></i> Importação de Clientes</h2>

        <hr/>

        <p>
            Para a importação dos clientes o arquivo XML deve seguir o schema da exportação
            de clientes do sistema TOTVS - Gestão de Estoques Compras e Faturamento.
        </p>

        <p>
            Para exportar o arquivo acesse o cadastro de clientes -> Processos -> Exportação de XML de clientes
        </p>

        <hr/>

        <form method="post" class="form-horizontal" id="usuario" enctype="multipart/form-data">
            <div class="row-fluid">
                <div class="span12">
                    <div class="control-group">
                        <label class="control-label">
                            <label for="senha">Arquivo XML</label>
                        </label>
                        <div class="controls">
                            <input type="file" name="arquivo" id="arquivo" class="input-xlarge">							
                        </div>
                    </div>
                </div>
            </div>

            <div class="form-actions">
                <input type="submit" id="submitbutton" class="btn btn-primary" value="Importar">  
                <a href="/clientes" class="btn">Cancelar</a>
            </div>

        </form>

        <?php if (isset($this->processados)) : ?>
            <h3>Clientes Processados: <?php echo $this->processados; ?></h3>
        <?php endif; ?>

        <?php if (isset($this->erros)): ?>
            <?php foreach ($this->erros as $erro) : ?>
                <p><?php echo $erro; ?></p>
            <?php endforeach; ?>
        <?php endif; ?>

        <script type="text/javascript">
            $('#usuario').validate({
                rules: {
                    arquivo: {required: true}
                }
            });
        </script>
    </div>
</div>
